connect_idx = {
    12: 'a photo of a person holding a bicycle',
    27: 'a photo of a person holding a bird',
    49: 'a photo of a person holding a bottle',
    79: 'a photo of a person holding a cat',
    88: 'a photo of a person holding a chair',
    99: 'a photo of a person holding a cow',
    116: 'a photo of a person holding a dog',
    132: 'a photo of a person holding a horse',
    147: 'a photo of a person holding a motorcycle',
    172: 'a photo of a person holding a potted plant',
    178: 'a photo of a person holding a sheep',
    202: 'a photo of a person holding an apple',
    210: 'a photo of a person holding a backpack',
    219: 'a photo of a person holding a banana',
    227: 'a photo of a person holding a baseball bat',
    233: 'a photo of a person holding a baseball glove',
    269: 'a photo of a person holding a cake',
    278: 'a photo of a person holding a carrot',
    285: 'a photo of a person holding a cell phone',
    
    292: 'a photo of a person holding a clock',
    298: 'a photo of a person holding a cup',
    331: 'a photo of a person holding a fork',
    339: 'a photo of a person holding a frisbee',
    354: 'a photo of a person holding a handbag',
    366: 'a photo of a person holding a keyboard',
    372: 'a photo of a person holding a kite',
    378: 'a photo of a person holding a knife',
    384: 'a photo of a person holding a laptop',
    395: 'a photo of a person holding a mouse',
    401: 'a photo of a person holding an orange',
    409: 'a photo of a person holding an oven',
    424: 'a photo of a person holding a pizza',
    431: 'a photo of a person holding a refrigerator',
    435: 'a photo of a person holding a remote',
    443: 'a photo of a person holding a sandwich',
    447: 'a photo of a person holding a scissors',
    457: 'a photo of a person holding a skateboard',
    466: 'a photo of a person holding a skis',
    484: 'a photo of a person holding a spoon',
    509: 'a photo of a person holding a suitcase',
    519: 'a photo of a person holding a surfboard',
    530: 'a photo of a person holding a teddy bear',
    541: 'a photo of a person holding a tie',
    560: 'a photo of a person holding a toothbrush',
    578: 'a photo of a person holding an umbrella',
    585: 'a photo of a person holding a vase',
}